export const enum Icon {
  BOFANG = "#icon-bofang", 
  ZANTING = "#icon-zanting",
  YINLIANG = "#icon-yinliang", 
  YINLIANG1 = "#icon-yinliang1", 
  ERJI = "#icon-erji", 
  SOUSUO = "#icon-sousuo", 
  XIAZAI = "#icon-xiazai",
  ZHEDIE = "#icon-jiantou-xia-cuxiantiao", 
  SHANGYISHOU = "#icon-ziyuanldpi", 
  XIAYISHOU = "#icon-ziyuanldpi1",
  JINGYIN = "#icon-yinliangjingyinheix", 
  LIEBIAO = "#icon-liebiao", 
  Dislike = "#icon-xihuan1",
  Like = "#icon-xihuan",
  Support = "#icon-zan",
  XUNHUAN = "#icon-xunhuan",
  LUANXU = "#icon-xunhuan1", 
}
